# file read and write

In [1]:
import numpy as np
from pandas import Series,DataFrame
import pandas as pd

In [3]:
# Can open csv files as a dataframe
dframe = pd.read_csv('data/lec25.csv')

#Show
dframe

q  r  s  t   apple
0  2  3  4  5    pear
1  a  s  d  f  rabbit
2  5  2  5  7     dog

In [5]:
# Can also use read_table with ',' as a delimiter
dframe = pd.read_table('data/lec25.csv',sep=',')

#Show
dframe

q  r  s  t   apple
0  2  3  4  5    pear
1  a  s  d  f  rabbit
2  5  2  5  7     dog

In [6]:
#If we dont want the header to be the first row
dframe = pd.read_csv('data/lec25.csv',header=None)

#Show
dframe

0  1  2  3       4
0  q  r  s  t   apple
1  2  3  4  5    pear
2  a  s  d  f  rabbit
3  5  2  5  7     dog

In [8]:
# We can also indicate a particular number of rows to be read
# 只读两行
pd.read_csv('data/lec25.csv',header=None,nrows=2)

0  1  2  3      4
0  q  r  s  t  apple
1  2  3  4  5   pear

In [ ]:
# Now let's see how we can write DataFrames out to text files
dframe.to_csv('mytextdata_out.csv')

#You'll see this file where you're ipython Notebooks are saved (Usually under my documents)

In [9]:
#  We can also use other delimiters

#we'll import sys to see the output
import sys 

#Use sys.stdout to see the output directly and not save it
dframe.to_csv(sys.stdout,sep='_')

_0_1_2_3_4
0_q_r_s_t_apple
1_2_3_4_5_pear
2_a_s_d_f_rabbit
3_5_2_5_7_dog


In [10]:
#We can also choose to write only a specific subset of columns
dframe.to_csv(sys.stdout,columns=[0,1,2])

,0,1,2
0,q,r,s
1,2,3,4
2,a,s,d
3,5,2,5


In [12]:
# 平时自己习惯用
dframe[[0,1,2]].to_csv(sys.stdout)

,0,1,2
0,q,r,s
1,2,3,4
2,a,s,d
3,5,2,5


# JSON

In [13]:
json_obj = """
{   "zoo_animal": "Lion",
    "food": ["Meat", "Veggies", "Honey"],
    "fur": "Golden",
    "clothes": null, 
    "diet": [{"zoo_animal": "Gazelle", "food":"grass", "fur": "Brown"}]
}
"""

In [14]:
#Let import json module
import json

#Lets load json data
data = json.loads(json_obj)

In [15]:
data

{u'clothes': None,
 u'diet': [{u'food': u'grass', u'fur': u'Brown', u'zoo_animal': u'Gazelle'}],
 u'food': [u'Meat', u'Veggies', u'Honey'],
 u'fur': u'Golden',
 u'zoo_animal': u'Lion'}

In [16]:
#WE can also convert back to JSON
json.dumps(data)

'{"food": ["Meat", "Veggies", "Honey"], "zoo_animal": "Lion", "fur": "Golden", "diet": [{"food": "grass", "zoo_animal": "Gazelle", "fur": "Brown"}], "clothes": null}'

In [17]:
#We can simply open JSON data after loading with a DataFrame
dframe = DataFrame(data['diet'])

In [18]:
dframe

food    fur zoo_animal
0  grass  Brown    Gazelle

# Merge

In [23]:
# Let's make a dframe

dframe1 = DataFrame({'key':['X','Z','Y','Z','X','X'],'data_set_1': np.arange(6)})

#Show
dframe1

data_set_1 key
0           0   X
1           1   Z
2           2   Y
3           3   Z
4           4   X
5           5   X

In [24]:
#Now lets make another dframe

dframe2 = DataFrame({'key':['Q','Y','Z'],'data_set_2':[1,2,3]})

#Show
dframe2

data_set_2 key
0           1   Q
1           2   Y
2           3   Z

In [25]:
# Now we can use merge the dataframes, this is a "many-to-one" situation

# Merge will automatically choose overlapping columns to merge on

# 默认上是inner merge，根据两个df中相同的column
pd.merge(dframe1,dframe2)

#Note no overlapping 'X's

data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2

In [26]:
# We could have also specified which column to merge on
# 一般我们需要明确的指定如何merge
pd.merge(dframe1,dframe2,on='key')

data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2

In [27]:
# We can choose which DataFrame's keys to use, this will choose left (dframe1)
# 这里指定使用左边的key作为参考，如果在被merge df没有出现的值，将使用NaN来填充
pd.merge(dframe1,dframe2,on='key',how='left')

data_set_1 key  data_set_2
0           0   X         NaN
1           1   Z           3
2           2   Y           2
3           3   Z           3
4           4   X         NaN
5           5   X         NaN

In [28]:
# Choosing the one on the right (dframe2)
pd.merge(dframe1,dframe2,on='key',how='right')

data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2
3         NaN   Q           1

In [29]:
#Choosing the "outer" method selects the union of both keys
# 使用outer的话，我们将会得到key的并集
pd.merge(dframe1,dframe2,on='key',how='outer')

data_set_1 key  data_set_2
0           0   X         NaN
1           4   X         NaN
2           5   X         NaN
3           1   Z           3
4           3   Z           3
5           2   Y           2
6         NaN   Q           1

In [30]:
#Now we'll learn about a many to many merge

# Note that these DataFrames contain more than one instance of the key in BOTH datasets

dframe3 = DataFrame({'key': ['X', 'X', 'X', 'Y', 'Z', 'Z'],
                 'data_set_3': range(6)})
dframe4 = DataFrame({'key': ['Y', 'Y', 'X', 'X', 'Z'],
                 'data_set_4': range(5)})

In [31]:
dframe3

data_set_3 key
0           0   X
1           1   X
2           2   X
3           3   Y
4           4   Z
5           5   Z

In [32]:
dframe4

data_set_4 key
0           0   Y
1           1   Y
2           2   X
3           3   X
4           4   Z

In [33]:
# 因为双方的key有比较多的重叠，合并后的条目有3*2 + 1*2 + 2*1 = 10
# 这就是many-to-many merge
pd.merge(dframe3, dframe4)

data_set_3 key  data_set_4
0           0   X           2
1           0   X           3
2           1   X           2
3           1   X           3
4           2   X           2
5           2   X           3
6           3   Y           0
7           3   Y           1
8           4   Z           4
9           5   Z           4

In [34]:
# We can also merge with multiple keys!

# Dframe on left
df_left = DataFrame({'key1': ['SF', 'SF', 'LA'],
                  'key2': ['one', 'two', 'one'],
                  'left_data': [10,20,30]})

#Dframe on right
df_right = DataFrame({'key1': ['SF', 'SF', 'LA', 'LA'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'right_data': [40,50,60,70]})

In [35]:
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [36]:
df_right

key1 key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [37]:
#Merge
pd.merge(df_left, df_right, on=['key1', 'key2'], how='outer')

key1 key2  left_data  right_data
0   SF  one         10          40
1   SF  one         10          50
2   SF  two         20         NaN
3   LA  one         30          60
4   LA  two        NaN          70

In [38]:
#Note that the left and right DataFrames have overlapping key names (key1 and key2).
# pandas automatically adds suffixes to them
# 遇到双方相同column名字的时候，会重命名column
pd.merge(df_left,df_right,on='key1')

key1 key2_x  left_data key2_y  right_data
0   SF    one         10    one          40
1   SF    one         10    one          50
2   SF    two         20    one          40
3   SF    two         20    one          50
4   LA    one         30    one          60
5   LA    one         30    two          70

In [39]:
# 可以指定column名
pd.merge(df_left,df_right, on='key1',suffixes=('_lefty','_righty'))

key1 key2_lefty  left_data key2_righty  right_data
0   SF        one         10         one          40
1   SF        one         10         one          50
2   SF        two         20         one          40
3   SF        two         20         one          50
4   LA        one         30         one          60
5   LA        one         30         two          70

# Merge on Index

In [40]:
# Lets get two dframes

df_left = DataFrame({'key': ['X','Y','Z','X','Y'],
                  'data': range(5)})
df_right = DataFrame({'group_data': [10, 20]}, index=['X', 'Y'])

In [41]:
df_left

data key
0     0   X
1     1   Y
2     2   Z
3     3   X
4     4   Y

In [42]:
df_right

group_data
X          10
Y          20

In [46]:
# 其实就是各自指定双方各自的key， 而index也是可以被当做为keyy

In [43]:
#Now merge, we'll use the key for the left Dframe, and the index for the right
pd.merge(df_left,df_right,left_on='key',right_index=True)

data key  group_data
0     0   X          10
3     3   X          10
1     1   Y          20
4     4   Y          20

In [44]:
# We can also get a union by using outer
pd.merge(df_left,df_right,left_on='key',right_index=True,how='outer')

data key  group_data
0     0   X          10
3     3   X          10
1     1   Y          20
4     4   Y          20
2     2   Z         NaN

In [45]:
#Now let's try something a little more complicated, remember hierarchal index?
df_left_hr = DataFrame({'key1': ['SF','SF','SF','LA','LA'],
                   'key2': [10, 20, 30, 20, 30],
                   'data_set': np.arange(5.)})
df_right_hr = DataFrame(np.arange(10).reshape((5, 2)),
                   index=[['LA','LA','SF','SF','SF'],
                          [20, 10, 10, 10, 20]],
                   columns=['col_1', 'col_2'])

In [47]:
#SHOW
df_left_hr

data_set key1  key2
0         0   SF    10
1         1   SF    20
2         2   SF    30
3         3   LA    20
4         4   LA    30

In [48]:
#Show, this has a index hierarchy
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [49]:
# Now we can merge the left by using keys and the right by its index
pd.merge(df_left_hr,df_right_hr,left_on=['key1','key2'],right_index=True)

data_set key1  key2  col_1  col_2
0         0   SF    10      4      5
0         0   SF    10      6      7
1         1   SF    20      8      9
3         3   LA    20      0      1

In [50]:
# We can alo keep a union by choosing 'outer' method
pd.merge(df_left_hr,df_right_hr,left_on=['key1','key2'],right_index=True,how='outer')

data_set key1  key2  col_1  col_2
0         0   SF    10      4      5
0         0   SF    10      6      7
1         1   SF    20      8      9
2         2   SF    30    NaN    NaN
3         3   LA    20      0      1
4         4   LA    30    NaN    NaN
4       NaN   LA    10      2      3

# Concatenate

In [54]:
# First in just Numpy
# Create a matrix 
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
# Concatenate along axis 1
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [56]:
# Let's see other axis options
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
# 看看在pandas下的操作
ser1 =  Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

#Now let use concat (default is axis=0)
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [58]:
# Now passing along another axis will produce a DataFrame
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [59]:
# We can specify which specific axes to be used
# 指定需要的index
pd.concat([ser1,ser2],axis=1,join_axes=[['U','V','Y']])

0   1
U   1 NaN
V   2 NaN
Y NaN   4

In [60]:
# Lets say we wanted to add markers.keys to the concatenation result

# WE can do this with a hierarchical index
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [61]:
# Along the axis=1 then these Keys become column headers
pd.concat([ser1,ser2],axis=1,keys=['cat1','cat2'])

cat1  cat2
T     0   NaN
U     1   NaN
V     2   NaN
X   NaN     3
Y   NaN     4

In [62]:
#Lastly, everything works similarly in DataFrames

dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [63]:
#Concat on DataFrame
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -1.256687 -1.222438 -1.133118
1       NaN  0.726479 -0.722988  0.212926
2       NaN  0.151096  0.555974 -1.240276
3       NaN  0.165450  1.277996 -0.254625
0 -0.516169  0.852616 -1.054367       NaN
1 -1.209989  0.231530 -0.071854       NaN
2  1.115575 -0.039990  0.729530       NaN

In [64]:
#If we dont care about the index info and just awnt to make a complete DataFrame, just use ignore_index
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -1.256687 -1.222438 -1.133118
1       NaN  0.726479 -0.722988  0.212926
2       NaN  0.151096  0.555974 -1.240276
3       NaN  0.165450  1.277996 -0.254625
4 -0.516169  0.852616 -1.054367       NaN
5 -1.209989  0.231530 -0.071854       NaN
6  1.115575 -0.039990  0.729530       NaN

In [65]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'